### ISSUE TITLE
Token Harvested but not validated

### ISSUE THREAD

**Issue by drun30** [J-M1/Recaptcha-V3-Harvester#2]
Once that the token is harvested, [it needs to be validated through recaptcha V2 or invisible recaptcha ](https://developers.google.com/recaptcha/docs/v3) sending a POST request to 'https://www.google.com/recaptcha/api/siteverify?secret=${secret-key}&response=${harvestedToken}', otherwhise it is rejected by the website. 

The problem is that of course the secret-key is not accesible on the client-side and setting the token as value of #g-recaptcha-response is ineffective for validation. 

Is there any method for validating the harvested tokens on the client -side?

**Comment by drun30** [comment]
may I ask you why you closed this issue?

**Comment by J-M1** [comment]
@drun30 This is not an issue with the harvester.

**Comment by drun30** [comment]
it is, since that the harvested tokens are invalid
